show tables;
SELECT * FROM librarysystem.book_fines;
SELECT * FROM librarysystem.book_renewals;
SELECT * FROM librarysystem.books;
SELECT * FROM librarysystem.employee;
SELECT * FROM librarysystem.issuebook;
SELECT * FROM librarysystem.librarian;
SELECT * FROM librarysystem.library_card;
SELECT * FROM librarysystem.publisher;
SELECT * FROM librarysystem.return_book;
SELECT * FROM librarysystem.student;
SELECT * FROM librarysystem.studyroom;
SELECT * FROM librarysystem.tech_id;
